### ISSUE TITLE
Security hole

### ISSUE THREAD

**Issue by QinxinTian** [PendragonGame/pendragon#147]
<img width="1275" alt="2017-11-04 4 39 14" src="https://user-images.githubusercontent.com/25886116/32403841-52abbc1c-c11a-11e7-975a-8ceef92a1bb5.png">

**Comment by anand-bala** [comment]
@QinxinTian you are just editing the web page locally, and it does not affect anything as it is just a statically generated website.

You can do the same with Google.com
