### ISSUE TITLE
Player needs direction fix when not walking. Player also collides with white space of trees.

### ISSUE THREAD

**Issue by brianbad** [PendragonGame/pendragon#36]
The player should continue facing the direction they were walking when they stop walking, not always turn forward.

The Player also should be able to stand a bit closer to the pine trees.

**Comment by anand-bala** [comment]
@brianbad The player facing the correct direction is fixed by #37

**Comment by anand-bala** [comment]
Try looking at [Terrain brush](http://doc.mapeditor.org/en/latest/manual/using-the-terrain-tool/) for the collision with houses and trees.

**Comment by anand-bala** [comment]
Also, this can be relegated to low priority.
