### ISSUE TITLE
Dead Entities at the Top of a Layer

### ISSUE THREAD

**Issue by sriram1996** [PendragonGame/pendragon#87]
When the player kills a monster or npc, he is able to walk underneath the deceased monster/npc so the layering is a little messed up but this is an issue to be solved after the MVP and preferably done for the beta-release

**Comment by anand-bala** [comment]
@jacobbel  @brianbad, check out this issue. I suspect the hacky fix is to loop through all dead entities in all the groups and send these entities to the bottom of the layer.

**Comment by anand-bala** [comment]
A possible, non-hacky, solution would be to remove the dead entities from the Entity group, and put it in something like a dead-entity group

**Comment by anand-bala** [comment]
@jacobbel @brianbad
